### ISSUE TITLE
Ask about the logit_bias of knowledge_query()

### ISSUE THREAD

**Issue by Alchemistyui** [sanjayss34/codevqa#1]
Hi, thanks for providing this wonderful work!
I'm interested in it and trying to reproduce the result. I see there is a [token ID dict in your code](https://github.com/sanjayss34/codevqa/blob/59b290db64f0f5273017a57926f2074ff60166a1/lavis/models/pnp_vqa_models/pnp_vqa.py#L996C29-L996C29):

> {1906: -100, 7200: -100, 284: -100, 532: -100, 12: -100, 11: -100, 14: -100}

Could you please tell me which word each of these token ID stand for? I want to change the LLM model to another one, but I didn't find a good way to map the token ID back to the words.

Looking forward to your reply, and thank you in advance.

**Comment by sanjayss34** [comment]
Hi, I think that having that dictionary and preventing the generation of those tokens isn't very important for reproducing roughly the same results (note it's only used for OK-VQA, since it's for knowledge-based questions). But these are the corresponding tokens:
```
{1906: '–', 7200: '°', 284: ' to', 532: ' -', 12: '-', 11: ',', 14: '/'}
```
Note that you can use the `tiktoken` package to convert between token IDs of OpenAI models and tokens.
